apiVersion: ENC[AES256_GCM,data:ZpM=,iv:2xrvIa+DDoaFP3W+HyURwybtMquiU8b50diggPhSCGs=,tag:Dr55AHVOL0rUNIl+8DISWA==,type:str]
kind: ENC[AES256_GCM,data:4Cz+JsaA,iv:3MrpTUgWMp4au94S4oqSWsJjK1/10ZWA1dKGtRfT4UM=,tag:Kfwl9AUb9wzWTR9BCYHIvA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lMZTSMUu2zBJVKWqWfJTEV7XqE4=,iv:TzPNB6tvLyrgmzUP3bLIdK2/oI4Se3OQaD06PheA6SA=,tag:GjQ3acIeXwK3aeu2UMZrfA==,type:str]
    namespace: ENC[AES256_GCM,data:zpHvTaJ9oVfBA4k=,iv:Oel/LM4CtCtglyXzGBY/fFJehlblpxKmA/CeQh4JKU4=,tag:SXMbEZGHnE/KNfW2YF/Zyg==,type:str]
type: ENC[AES256_GCM,data:S6FZcNf1nc5sCzZBcUAqzg6UJrfywy0d5E98YMAr,iv:FSc7Rvu8/SGicpRekMrYpHitscjRO7XKUAG7XwowNFA=,tag:/SI2rhN5taeqFZnZw+FQRA==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:x+89q68ocGAwYVOqLB8qd9dd+hG1V0WwrQ1GLu0Rk5ra20NJ9bCmU/hw69HVqOiZZ08GiLBux3LC/wlX/YW3c5O5d4mt+9Gqpl4SyzQK0x7QbS5vc2FSB10kAzV5SeMXnl+4hGxpa9m5EouXp5+Tp2qjQ2a59LCYCeFABXuOBpArYbbO3eSw5k0CRRAbp9eF/tD7zA==,iv:dx8suyMxwKMYZvfld7aRroXtlDYaEL4rbNTzjLIFUVM=,tag:SILEs2veLWJw3HZC3cCgwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3kwgf0lgv0594kgyrva7vja8cvws79xdsc4rv92fts2t5phn96s4984mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVUtqQVdKMEFyU2RCKzNX
            RjRLS0plV3NpOSswSVd4aVlCOGdxQ3ZyYzJrCnNSeko3bzZteWZjc0FSdWdFYm53
            N0s0SXdDUk5UNFNSNUVrdUlwcnl6WW8KLS0tIElGamtvS3ZCTjhDcnZ6c3YvU2Zt
            Mk5xMVZ4MFlMNEw4ai9UazcreHIvejQKqug0Xlqy45mfNaFTj7hPSfLVgRVJg60p
            NLtFt+uRpy+VV1bGvtxF+Vl7EOcoeHvILiqpDllt4uJmqvEFQvrlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T21:21:31Z"
    mac: ENC[AES256_GCM,data:+sPzYKhg1m1R2PoDTxH9R1wY5IbETyGTC/bgsiJtUDj6e0UAEFUzia7h1qC1ugtnK5nHXDmqRDTVUrtPr/DBD6fmWNmsAUkD+lD5IQeCu+cMQJLHwG9O39BB7aEXxDfkuIXp71zwRfdwd2K+DhGFcYYViY7iYiGn9P5XIAPaVHU=,iv:I7BZsQ5h0DgXwIXTtVfYRlOvIf5M/UHtz0Do2TJzOWM=,tag:p5U3vyL3hQUzytLSqKU2tA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
