apiVersion: ENC[AES256_GCM,data:V0g=,iv:jdttMwI+ScrWl/4DxTig756XhXi3ptulEZqjhkgt3P0=,tag:t4mBnzQT5AbSQ1s9KDnhww==,type:str]
kind: ENC[AES256_GCM,data:kaVMv+r6,iv:ph9KyA0YL7FuvB0SyNfTpUrP8cK0fjFUrq8d7P6hhDY=,tag:FupAtQrlpjs1QCDsR1MSZw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M9K4f+og98nd9WJ0774=,iv:9k23URIaSrvynlozFx1Q2hHvPoXRJ4vkB23LiOVskng=,tag:b72AqI3yophWSJBUkSm/uA==,type:str]
    namespace: ENC[AES256_GCM,data:Hc0elKuy61TP+9k=,iv:cadhz+ddCLKUiJ6jH+DDr9l1qUYQlkwaqM5PE1oPf8I=,tag:0GyClo7xmb138dnGw3P+RA==,type:str]
type: ENC[AES256_GCM,data:8W/L4nlIT/5H3X0f5LqUbbKHQW+Vpfq9vMw2HtLa,iv:hbd5aL8AvSAvUdbn+2cYlsNfDkkRsbVJf0Yk/7wQAvs=,tag:W+zM5CWi36/mXaZZNJBoww==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8rmDm7KR8vYBBMM37LAjoYma4oRfzI/oLBwj42N52to97rApU2jczDuutK4Rl3qF3OBYCurvauoW2+97Sjhu8pvX556t78h7MzWOQ5Aj20dn6Zhl5uCnI5j7dWWzC5ZGyyJfe8IOctQWxuaG8XyLMn1p+lRigQMZD1A9412AYg5vTvrA4SlG0I+Zll/FfBRK0eMA/7XKrqbx1IzinjKJ5m+0e+3v+2PVWibpadnBfKosc2NiPOLmTJTK8kFG5/pgqGmPm6EoQ/o=,iv:4cXFE2xGNrnBtOSoHqlVyyim6I5EV+PUbnpEYNGsIKs=,tag:aceaU5VLY4y+/qgfzJInvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3kwgf0lgv0594kgyrva7vja8cvws79xdsc4rv92fts2t5phn96s4984mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWm1GN2xOZVZPd2N2cDlp
            c3c4NysxUS9aekw3U3BNRE5JUGs3OWVSVEc0Cm5GVjhqUGFWZWxvZk1zajRiakNZ
            T25obnVJaEREQXNtb1d3TmdGS1dVTncKLS0tIG4xS0FmelhLdVl1Qy9ZVXFMUXB4
            UUZ4Vmhiejlzb0tNZHBRNnRqUDh1MFEKmH2I1Vifeu/Ka9n4+ueDmy3AHf+xAAvj
            CwexdgPgYaCIvnmsWJu0BigvZkXXCCJRkF+DTojeQxfGuD5crkJR9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T20:38:09Z"
    mac: ENC[AES256_GCM,data:hifqcL4MD4ZiiQizY+sGGibOUFWcQI9GR7ooNnjz6EMNBS/dvIGxpcauh/YBQXHGhWHQq0X5hJhX7AaeZZLEVGxRVA4fnoMhljgs05yXgf/85MVWOgAfYZwwnYoEyREjM7e7MoXQfAFjDEl5/fdlaOn6ptOOS7FqsAE4QkwhC4c=,iv:V56si55uYGjLezqksrssFSR3UTzqwEW/KuM1iA/gMVE=,tag:vO8c3UpkEcRy16UlA761SA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
