apiVersion: ENC[AES256_GCM,data:6U4=,iv:K+4KOKJGw6e6exsr5kaZnKWaZnP4HxF39PpBkBjJbg4=,tag:7IX6OlFjXhLfsL5AGrlPHg==,type:str]
kind: ENC[AES256_GCM,data:wvhmkuPf,iv:kk5jbQyi6Atk0Wy7GCWB3BbcS9S/QAGuV024bHd57RQ=,tag:GU5x7PVrsZy5M8DXgzTlsQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GWX85ZbFx/3nZr+0S1QE634d6F/cCgAfmQQ=,iv:HY3qIyxYZZko0Ucfh08HdmsVnJ/mv2GB2vsFEu7q2Kg=,tag:at97aCHtAkPCGpEJ61Jghw==,type:str]
    namespace: ENC[AES256_GCM,data:5iX4XknUG4cnA54=,iv:bMoTvR5MEXxS1Oa+pfk1FxNV931rDVymTm9XK3pNcZA=,tag:UbPiW6MfQhStrDKjp05Mvw==,type:str]
type: ENC[AES256_GCM,data:r5PYvNSkigcVTZ9P358HlueCBEUBZVDPQ6G6Ywje,iv:u/fH2dWaPwpJ3GKeQkBNc0uuzSbyYdPi9LaKKrXz9qo=,tag:qOffzVW17TJ3h1cvs3etGw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:X3bdaXF21UOKk18KocO5/m7ltJdPwNmSDbxFW9RZuzfta493JMG/V3/LhAzfqHgSbGZiyXbK/+ZEYEzFh7XcV51VZLVS7nKutO1NtlTJGYFLMiqi0EOL0F4b3CS3S51FOyMu78QML5lOEJ2hnFSQaqv0UcSf8k/DUGuJMMKBRO+w75110d+0m5pan3XOdYJsXbp+uA==,iv:DDuAxCih4MGcsUdiuBmoJFw/r+ssC1YzXVQ7U1hhVGg=,tag:2RkBBRz3Zmqdy8VTa9AyPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3kwgf0lgv0594kgyrva7vja8cvws79xdsc4rv92fts2t5phn96s4984mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOUtMSEQxcmVwRnNta3Jv
            MVhUSnZVdmhjdXlONTdpZEZIMVk0SEkzaW5NCmRvaThTd0pla242MVRFRVFSMmIz
            YWh5L2kvdVBIZEdaL0ZWcGtXajlRS2cKLS0tIHhTWDc2QXFtMlVscXR4T1VIa1c3
            dEw4MGc0dWdrYjJ4blpWdDMxV0RheU0K66D8P+3pCC9s1v5xxon4LGoAa9s0QUe3
            q0TTZZFFt+wsBW736DxlDYuGoi9LNjZcnycbdJDblSD/8wiJxEGf1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T20:38:09Z"
    mac: ENC[AES256_GCM,data:yGsx/ePtNqw1JKvQiruRJ18o2sEd9V5/hG3Vlw8FTv2RLsyyy0D0gihXAqlzDi49NrCawgHyW+KghxyhBvb6Jcj9HwykqpY+1aE1kUdWMumfaEvaMeq96XJUG2JRMCWTcAn1BVr7L5YueMNuJNpIE403l0Ef4+brKwBppbeAt1c=,iv:4osGmf5Va0We+4yJKxW4AnnSnYVYLZDW24qC8iXE1Os=,tag:5+R2Bm/V00/TfsE5IeSLGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
