apiVersion: ENC[AES256_GCM,data:JrY=,iv:4LGGmyxiIbEVn/a1fE81zJLTqEyx8cB1jVB7wUQhLPY=,tag:cJ7Fdmmkugts3uBslTDkNg==,type:str]
kind: ENC[AES256_GCM,data:mpD2UAvB,iv:RSz8KSBH2aub0j7N3zDaRjOnDUNexz0IAH0/FmCMOgo=,tag:QgSz0JMPXMhJEGRnOvxfKg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ObbGVWiXU40Bl7B2iBC5,iv:ROsHgmDKqY/FSPnZtKRc8QUIiRVhiQnw/Ylxv3g2CmA=,tag:0pWDmV1g6FD+XagLAu1USQ==,type:str]
    namespace: ENC[AES256_GCM,data:jYGNhNcvoC6gSQ==,iv:UnOtu/kkoVLtA6nsi7MiJPjjeOw5xH65a3aRvgoE6hY=,tag:e2e1JJ+nmXxetUV25IVzYw==,type:str]
type: ENC[AES256_GCM,data:WSlrvBbr,iv:sv21fxJDB2SDVs+bGWTxmsHmkYJdxIbbkGnlsPpcX18=,tag:6x3mN0RkrEbzZbfWB2G/KQ==,type:str]
data: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3kwgf0lgv0594kgyrva7vja8cvws79xdsc4rv92fts2t5phn96s4984mt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6amRyYW1SYnRsYWJiMFNR
            aEhpV1ZIKzM5WEdnLzNBU0NJRTdlZkRLdjNvCmk2eUU0alJSRXI5ajlaZXZwZ2Ew
            VXdOQys4UTJPMjUxT2RGSVVmb3QreDAKLS0tIGNEZ2xJWHBvc2hFRXB5aFY4bTZl
            ekxrNXBrK3NGYytjRTFjWjJnZVVHMmsKtr/hhlhkzq9zTD/L1uD+mG9NsH+M6wCT
            AhSGT3f40YCxIrOPbusJcK1oWi9ZHw0Q22uqaQsoBs7iXtEzetcqNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T20:38:09Z"
    mac: ENC[AES256_GCM,data:gVhK4bPK73tq/puONfNP9q+kqVShxF7KUrMsBJyK94+Ibp9XSA5YqY1pdrQCjxe090QyQjy4afs3rPLYCKKOjibRowEKexB+UHfeXKSkitMVkmH5pyAnNJzQE90/Cvl9iH94yXd7VCDTz4PQ0KnBF+z1yyEm1I+ul1rpouLoyOk=,iv:yD2T4v3ywPa1kwitsy78ZFGfWnrfYBwH9e8cM3RREbs=,tag:yFElH9+ro8gG9ezhgsIEGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
