apiVersion: v1
data:
  values.yaml: Y2VpcF9wb2xpY3lfZGlzY2xvc2VkOiB0cnVlCmFwaV9pbmdyZXNzOgogIGZxZG46IGFwaS5rOHNhZ2UuY29tCiAgdGxzOgogICAgbmFtZXNwYWNlOiB0YXAtaW5zdGFsbAogICAgc2VjcmV0X25hbWU6IHRhcHRsc2NlcnQKYXBwX2luZ3Jlc3M6CiAgZGVmYXVsdF9kb21haW46IGs4c2FnZS5jb20KICB0bHM6CiAgICBuYW1lc3BhY2U6IHRhcC1pbnN0YWxsCiAgICBzZWNyZXRfbmFtZTogdGFwdGxzY2VydAphcHBfcmVnaXN0cnk6CiAgY3JlZGVudGlhbHM6CiAgICBzZWNyZXRfbmFtZTogdXNlci1yZWdpc3RyeS1kb2NrZXJjb25maWcKICAgIG5hbWVzcGFjZTogdGFwLWluc3RhbGwKICByZXBvc2l0b3J5X3ByZWZpeDogaGFyYm9yLms4c2FnZS5jb20vdGFzLWFkYXB0ZXIvCmFkbWluOgogIHVzZXJzOgogIC0gdGFzLWFkbWluCg==
kind: Secret
metadata:
  name: tas-adapter-tap-install-values
  namespace: tap-install
type: Opaque
